server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: http://localhost:5048
          predicates:
            - Path=/auth/**

        - id: students-service
          uri: http://localhost:5049
          predicates:
            - Path=/students/**

        - id: notes-service
          uri: http://localhost:5050
          predicates:
            - Path=/notes/**

        - id: course-rest
          uri: http://localhost:5051
          predicates:
            - Path=/course/rest/**

        - id: course-soap
          uri: http://localhost:5052
          predicates:
            - Path=/course/soap/**
          filters:
            - RewritePath=/course/soap/(?<segment>.*), /${segment}


        - id: billing-service
          uri: http://localhost:5185
          predicates:
            - Path=/billing/BillingService.svc/**
          filters:
            - StripPrefix=1


