# ---------- Build stage ----------
FROM golang:1.25.5-alpine3.23 AS builder

# Install gcc & sqlite deps
RUN apk add --no-cache gcc musl-dev sqlite-dev

WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build the binary
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o note-service

# ---------- Runtime stage ----------
FROM alpine:latest

# Install sqlite runtime libs
RUN apk add --no-cache sqlite-libs

WORKDIR /app

COPY --from=builder /app/note-service .

# Optionally copy .env if used
COPY .env .env

EXPOSE 5050

CMD ["./note-service"]
