spring.application.name=auth-service

server.port=9000

jwt.expiration = 9876543
jwt.secret = klrjklgerjhklbhjkesfjytdfsbhgdfbhjvdnjhdgfjhvbnwdgvbng

spring.datasource.url=jdbc:sqlite:auth.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
